FROM node:23-alpine3.20
WORKDIR /app
COPY .npmrc ./
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a

RUN npm install && npm install -g nodemon
EXPOSE 4007

CMD ["npm", "run", "dev"]
